SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE 
	WHERE TABLE_NAME = 'usuario_acesso' AND COLUMN_NAME = 'acesso_id' 
	AND CONSTRAINT_NAME <> 'unique_acesso_user';
	
ALTER TABLE usuario_acesso drop CONSTRAINT "ukfhwpg5wu1u5p306q8gycxn9ky";